version: "3"
services:
  db:
    image: postgres:12.7
    container_name: fastapi_todo_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data/pgdata
      - ./db/initdb:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  app:
    build: .
    container_name: fastapi_todo_app
    depends_on:
      - db
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./app:/app
    env_file:
      - .env
